training:
  name: dcgan
  args:
    out_shape: 64
    channels: 3
    project_name : test_again
    save_path : /mnt/data2/gan_results
    init : orthogonal #orthogonal
    

generator: 
  name: dcgan
  args: 
    out_shape : 64
    latent_dim: 100
    ch_multiplier : 2
    out_channels: 3
    block_type : resnet
    attention_at : [2]
    spectral_norm : true

discriminator:
  name: dcgan
  args:
    out_shape: 64
    in_channels : 3
    ch_multiplier : 2
    block_type : resnet
    activation : none #Sigmoid  #change bce with bce with logits
    spectral_norm : true
    minibatch_discrimination : false
    attention_at : [1]

loss:
  name: vanilla
  label_smoothing : true #only useful with normal vanilla loss -> name : vanilla, 
  # feature_matching # add lambda as hyperparameter
  lambda : 5

augmentation:
  args:
    kaka: 

dataset:
  name : ImageNet
  # data_path : /mnt/data2/datasets/lsun/train
  data_path : /mnt/data2/datasets/ImageNet
  return_labels : false

metrics : 
  fid : fid
  prd : prd #precision and recall 

  
params:
  has_labels : false
  batchsize: 128
  num_workers : 10
  latent_dim : 100
  lr_disc: 0.0004
  lr_gen : 0.0001
  logging_iterations : 500
  iterations : 100000
  beta1 : 0.0
  beta2 : 0.9
  n_crit : 1
  amp : false


