training:
  name: dcgan
  args:
    out_shape: 256
    channels: 3
    project_name : lsgan_lsun_256x256
    save_path : /mnt/data2/gan_results
    

generator: 
  name: wgan
  args: 
    out_shape : 256
    latent_dim: 100
    out_channels: 3
    # upsample_type : deconv

discriminator:
  name: dcgan
  args:
    out_shape: 256
    in_channels : 3
    net_type : "lsgan" #wgan, dcgan 

loss:
  name: lsgan

augmentation:
  args:
    kaka: 

dataset:
  name : general
  data_path : /mnt/data2/datasets/lsun/train
  
params:
  has_labels : false
  batchsize: 256
  num_workers : 10
  latent_dim : 100
  lambda : 10
  

