training:
  name: wgan
  args:
    out_shape: 64
    channels: 3
    project_name : spectral_norm_wgan_celeb
    save_path : /mnt/data2/gan_results
  
metrics : 
  fid : fid
  prd : prd #precision and recall 

generator: 
  name: dcgan
  args: 
    out_shape : 64
    latent_dim: 100
    out_channels: 3
    block_type : resnet

discriminator:
  name: dcgan
  args:
    out_shape: 64
    in_channels : 3
    activation : none
    block_type : resnet
    spectral_norm : true

loss:
  name: wgan_gp
  label_smoothing : false

augmentation:
  args:
    kaka: 

dataset:
  name : general
  data_path : /mnt/data2/datasets/celebA/img_align_celeba/
  
params:
  has_labels : false
  batchsize: 256
  num_workers : 10
  latent_dim : 100
  lr_disc: 0.0001
  lr_gen : 0.0002
  iterations : 30000
  logging_iterations : 1000
  beta1 : 0.0
  beta2 : 0.9
  lambda : 10
  c : 0.01
  lambda : 10
  n_crit : 5  

mode : gp #clipping




#umstellen auf iterations nicht epochen  sp#äter